name: 'Close stale PR and Issues'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-message: 'This PR is stale because it has been open 365 days with no activity. Remove stale label or comment or this will be closed in 30 days.'
          days-before-pr-stale: 365
          days-before-pr-close: 30
          stale-issue-message: 'This issue is stale because it has been open 365 days with no activity. Remove stale label or comment or this will be closed in 30 days.'
          close-issue-reason: 'not_planned'
          days-before-issue-stale: 365
          days-before-issue-close: 30
         
